[UniWav]
BandwidthExpantion=40; Hz BandwidthExpantionCoef=1-BandWidtExpansion*pi/16000 (FreqSamplingRate)
Bottom_Loudness=-52  ; for aud-file power bottom == max(Bottom_Loudness,location_of_first_min_after_first_max)
sound_volume_chunk=10;
SimilZero=2;	
ComfortableNoise=40;	
allowed_duration_sec=150;	
;Normal_Loudness=-6;  

[PNP]
LPC_order=20;

[BFT]

logBark_IY = 1.3089   2.3927;
logBark_W =  1.4789   1.4798;
logBark_AA = 2.0865   1.6681;
energy_weight_min_dbm=-35;
energy_weight_max_dbm=-16;

minArticulationDuration_msec=30;
min_duration_for_insertion_msec=150;

[PHN]

;;; omitted ;;VICINITY=0.0001; relative constant = 0.01%. If distance between points is less then VICINITY*

max_fricat_flatB3=2.6; 
std_stop_factor=9.0;
maximal_ignorable_phone_length_after_closure=5;
no_speech_mean_power=-45;

[E:\AUDB\LIFEMI\TIMITLABEL\MSVS0]

essentialMaxF1 = 650;
essentialMinF3 =2200;
essentialMaxF3 =3600;