#include "StdAfx.h"
#include "aiVoxel.h"
#include "aiRender.h"
#include "aiDoorCollider.h"
#include "wInterface.h"
#include "Grid.h"
#include "aiPMconst.h"
namespace NAI
{
////////////////////////////////////////////////////////////////////////////////////////////////////
//					CVoxelCube
////////////////////////////////////////////////////////////////////////////////////////////////////
char CVoxelCube::GetObjectIntersectCode( NWorld::IVisObj *_pObject, int nTSFlags )
{
	CPtr<NWorld::IVisObj> pObject(_pObject);
	int nReturn;
	if ( !pObject )
		nReturn = 0;
	else
	{
		CObjectNumbers::iterator it = objectNumbers.find( pObject );
		if ( it != objectNumbers.end() )
			nReturn = it->second;
		else 
		{
			objectNumbers[ pObject ] = nReturn = nSpareNumber;
			if ( nTSFlags & ( NWorld::TS_STATE_OPEN | NWorld::TS_STATE_CLOSED ) )
			{
				nSpareNumber += ADC_ADD_TO_SPARE_NUMBER;
				if ( nSpareNumber > 255 )
					nSpareNumber = ADC_ADD_TO_SPARE_NUMBER;
				objects[ nReturn >> 2 ] = pObject;
			}
		}
	}
	if ( ( nTSFlags & NWorld::TS_STATE_OPEN ) == 0 )
		nReturn += ADC_CLOSED;
	if ( ( nTSFlags & NWorld::TS_STATE_CLOSED ) == 0 )
		nReturn += ADC_OPEN;
	return nReturn;
}
////////////////////////////////////////////////////////////////////////////////////////////////////
inline void CVoxelCube::CheckVoxel( int nCode, SDoorColliderAnalyzer *pAn )
{
	if ( nCode )                                            
	{
		pAn->pSrc = objects[ nCode >> 2 ];
		if ( nCode & ADC_OPEN )
			pAn->bInOpen = true;
		if ( nCode & ADC_CLOSED )
			pAn->bInClosed = true;
	}
}
////////////////////////////////////////////////////////////////////////////////////////////////////
inline void CVoxelCube::CheckCircle( int nX, int nY, int z, SDoorColliderAnalyzer *pAn )
{
	#define CHECK_VOX(x,y) CheckVoxel( intersectCodes[z][y+nY][x+nX], pAn );
		// this code was autogenerated
		CHECK_VOX(-3,-1);CHECK_VOX(-3,0);CHECK_VOX(-3,1);
		CHECK_VOX(-2,-2);CHECK_VOX(-2,-1);CHECK_VOX(-2,0);CHECK_VOX(-2,1);CHECK_VOX(-2,2);
		CHECK_VOX(-1,-3);CHECK_VOX(-1,-2);CHECK_VOX(-1,-1);CHECK_VOX(-1,0);CHECK_VOX(-1,1);CHECK_VOX(-1,2);CHECK_VOX(-1,3);
		CHECK_VOX(0,-3);CHECK_VOX(0,-2);CHECK_VOX(0,-1);CHECK_VOX(0,0);CHECK_VOX(0,1);CHECK_VOX(0,2);CHECK_VOX(0,3);
		CHECK_VOX(1,-3);CHECK_VOX(1,-2);CHECK_VOX(1,-1);CHECK_VOX(1,0);CHECK_VOX(1,1);CHECK_VOX(1,2);CHECK_VOX(1,3);
		CHECK_VOX(2,-2);CHECK_VOX(2,-1);CHECK_VOX(2,0);CHECK_VOX(2,1);CHECK_VOX(2,2);
		CHECK_VOX(3,-1);CHECK_VOX(3,0);CHECK_VOX(3,1);
	#undef CHECK_VOX
}
////////////////////////////////////////////////////////////////////////////////////////////////////
void CVoxelCube::SphereTest( int nX, int nY, float fH, SDoorColliderAnalyzer *pAn )
{
	int nLowerEdge = ( fH - F_TEST_SPHERE_RADIUS ) / F_VOXEL_HEIGHT + 1;
	int nUpperEdge = ( fH + F_TEST_SPHERE_RADIUS ) / F_VOXEL_HEIGHT + 1;
	int z = fH / F_VOXEL_HEIGHT + 1;
	CheckCircle( nX, nY, z, pAn );
	if ( pAn->IsCollided() )
		return;
	for ( int z = nLowerEdge; z < nUpperEdge; ++z )
	{
		CheckVoxel( intersectCodes[z][nY][nX], pAn );
		CheckCircle( nX, nY, z, pAn );
		if ( pAn->IsCollided() )
			return;
	}
}
////////////////////////////////////////////////////////////////////////////////////////////////////
void CVoxelCube::MovingSphereTest( int nX, int nY, float fH, int nDX, int nDY, float fDZ, SDoorColliderAnalyzer *pAn )
{
	pAn->bInClosed = pAn->bInOpen = false; pAn->pSrc = 0;
	float fX = nX, fDDX, fY = nY, fDDY, fZ = fH, fDDZ;
	int nTimes;
	if ( nDX == 0 && nDY == 0 )
	{
		int nLowerEdge1 = ( Min( fH, fH + fDZ ) - F_TEST_SPHERE_RADIUS ) / F_VOXEL_HEIGHT + 1;
		int nLowerEdge2 = Min( fH, fH + fDZ ) / F_VOXEL_HEIGHT + 1;
		int nUpperEdge1 = Max( fH, fH + fDZ ) / F_VOXEL_HEIGHT + 1;
		int nUpperEdge2 = ( Max( fH, fH + fDZ ) + F_TEST_SPHERE_RADIUS ) / F_VOXEL_HEIGHT + 1;
		for ( int z = nLowerEdge1; z < nLowerEdge2; ++z ) 
			CheckVoxel( intersectCodes[z][nY][nX], pAn );
		if ( pAn->IsCollided() )
			return;
		for ( int z = nLowerEdge2; z < nUpperEdge1; ++z ) 
		{
			CheckCircle( nX, nY, z, pAn );
			if ( pAn->IsCollided() )
				return;
		}
		for ( int z = nUpperEdge1; z < nUpperEdge2; ++z ) 
			CheckVoxel( intersectCodes[z][nY][nX], pAn );
		return; 
	}
	if ( abs(nDX) > abs(nDY) )
	{
		nTimes = abs(nDX);
		fDDX = Sign(nDX); 
		fDDY = (float)nDY / nTimes;
		fDDZ = (float)fDZ / nTimes;
	}
	else
	{
		nTimes = abs(nDY);
		fDDY = Sign(nDY); 
		fDDX = (float)nDX / nTimes;
		fDDZ = (float)fDZ / nTimes;
	}
	for ( int i = 0; i < nTimes; ++i ) 
	{
		int nLowerEdge = ( fZ - F_TEST_SPHERE_RADIUS ) / F_VOXEL_HEIGHT + 1;
		int nUpperEdge = ( fZ + F_TEST_SPHERE_RADIUS ) / F_VOXEL_HEIGHT + 1;
		int z = fZ / F_VOXEL_HEIGHT + 1;
		#define CHECK_VOX(x,y) CheckVoxel( intersectCodes[z][y+nY][x+nX], pAn );
		CHECK_VOX(-3,-1);CHECK_VOX(-3,0);CHECK_VOX(-3,1);
		CHECK_VOX(-2,-2);CHECK_VOX(-2,2);
		CHECK_VOX(-1,-3);CHECK_VOX(-1,3);
		CHECK_VOX(0,-3);CHECK_VOX(0,3);
		CHECK_VOX(1,-3);CHECK_VOX(1,3);
		CHECK_VOX(2,-2);CHECK_VOX(2,2);
		CHECK_VOX(3,-1);CHECK_VOX(3,0);CHECK_VOX(3,1);	
		#undef CHECK_VOX
		if ( pAn->IsCollided() )
			return;
		for ( z = nLowerEdge; z < nUpperEdge; ++z ) 
			CheckVoxel( intersectCodes[z][nY][nX], pAn );
		fX += fDDX;
		fY += fDDY;
		fZ += fDDZ;
		nX = fX, nY = fY;
	}
}
////////////////////////////////////////////////////////////////////////////////////////////////////
void CVoxelCube::MovingSphereTest( const CVec3 &ptCenter, const CVec3 &vel, SDoorColliderAnalyzer *pAn )
{
	float fX = ptCenter.x - ptOrig.x;
	float fY = ptCenter.y - ptOrig.y;
	const float fKoef = 6 / ( FP_GRID_STEP * FP_GRID_STEP );
	int nX = (  fX * ptXDir.x + fY * ptXDir.y ) * fKoef + 8;
	int nY = ( -fX * ptXDir.y + fY * ptXDir.x ) * fKoef + 8;
	int nDX = (  vel.x * ptXDir.x + vel.y * ptXDir.y ) * fKoef;
	int nDY = (  vel.y * ptXDir.x - vel.x * ptXDir.y ) * fKoef;
	MovingSphereTest( nX, nY, ptCenter.z, nDX, nDY, vel.z, pAn );
}
}
